---
-
  hosts: "UIUX_Server"
  name: "Enabling or Starting UIUX"
  tasks:
    - name: "Starting PM2 Service"
      command: "pm2 start ecosystem.config.js --only {{ customer_env }} --env development"
      args:
        chdir: /opt/PM2/UIUX_Deployments/
      become: yes

    - name: pm2 status
      shell: pm2 status | grep {{ customer_env }}
      become: yes
      register: pm2_status
    - debug: var=pm2_status.stdout_lines
...

