---
  #- command: /opt/cddb_3200/bin/mysql -N -u relusr -prelusr*1 -h 10.100.16.51 -P 3400 -D provisioningdb -e "UPDATE PROVISIONING_PROGRESS_V2 SET STARTDATE=NOW() WHERE CUSTOMER='{{ customer_name }}' AND LOB='{{ lob_name }}' AND MAIN_PLAY='{{ main_play }}' AND SUB_PLAYS='Node_Configuration.yml' AND ENVIRONMENT='{{ environment }}' AND STATUS='INPROGRESS';"

  - name: 'NGINX_CONFIGURATION'
    include_tasks: "{{ item }}"
    loop:
       - nginxconf_configuration.yml

  #- command: /opt/cddb_3200/bin/mysql -N -u relusr -prelusr*1 -h 10.100.16.51 -P 3400 -D provisioningdb -e "UPDATE PROVISIONING_PROGRESS_V2 SET ENDDATE=NOW() WHERE CUSTOMER='{{ customer_name }}' AND LOB='{{ lob_name }}' AND MAIN_PLAY='{{ main_play }}' AND SUB_PLAYS='Node_Configuration.yml' AND ENVIRONMENT='{{ environment }}' AND STATUS='COMPLETED';"
    
