---
     #- command: /opt/cddb_3200/bin/mysql -N -u relusr -prelusr*1 -h 10.100.16.51 -P 3400 -D provisioningdb -e "UPDATE PROVISIONING_PROGRESS_V2 SET STARTDATE=NOW() WHERE CUSTOMER='{{ customer_name }}' AND LOB='{{ lob_name }}' AND MAIN_PLAY='{{ main_play }}' AND SUB_PLAYS='mongodb_check.yml' AND ENVIRONMENT='{{ environment }}' AND STATUS='INPROGRESS';"

     - name: Check if Mongodb already installed
       shell: docker ps | grep mongo
       register: mongo_ver
       ignore_errors: True

     - name: When Mongodb is already installed
       debug: msg="Mongodb is already installed"
       when: mongo_ver is succeeded

     - name: Install Mongodb
       include: mongodb_install.yml
       when: mongo_ver is failed
      
     #- command: /opt/cddb_3200/bin/mysql -N -u relusr -prelusr*1 -h 10.100.16.51 -P 3400 -D provisioningdb -e "UPDATE PROVISIONING_PROGRESS_V2 SET ENDDATE=NOW() WHERE CUSTOMER='{{ customer_name }}' AND LOB='{{ lob_name }}' AND MAIN_PLAY='{{ main_play }}' AND SUB_PLAYS='mongodb_check.yml' AND ENVIRONMENT='{{ environment }}' AND STATUS='COMPLETED';"

