     - name: Creates Nodejs Install directory
       file:
         path: /home/Install
         state: directory

     - name: Unarchive a file
       ansible.builtin.unarchive:
         src:  https://nodejs.org/download/release/v12.18.1/node-v12.18.1-linux-x64.tar.xz
         dest: /home/Install
         remote_src: yes

     - name: copy
       shell: cp -r /home/Install/node-v12.18.1-linux-x64/{bin,include,lib,share} /usr
       become: yes
   
     - name: node version check
       shell: node -v
       register: node

     - debug:
         var: node.stdout_lines

     - name: npm version check
       shell: npm -v
       register: npm

     - debug:
         var: npm.stdout_lines

