---
# - name: install nodejs
#   hosts: localhost
#   become: true
# - tasks:
     - name: Check if node already installed
       shell: node -v
       register: node_ver
       ignore_errors: True

     - name: When Node is already installed
       debug: msg="Node is already installed"
       when: node_ver is succeeded

     - meta: end_play
       when: node_ver is succeeded

     - name: Install node
       when: node_ver is failed
       shell: echo "Going to install"       

     - name: Creates Install directory
       file:
         path: /home/Install
         state: directory

     - name: Unarchive a file
       ansible.builtin.unarchive:
         src:  https://nodejs.org/download/release/v12.18.1/node-v12.18.1-linux-x64.tar.xz
         dest: /home/Install
         remote_src: yes

     - name: copy
       shell: cp -r /home/Install/node-v12.18.1-linux-x64/{bin,include,lib,share} /usr

     - name: node version check
       shell: node -v
       register: node

     - debug:
         var: node.stdout_lines

     - name: npm version check
       shell: npm -v
       register: npm

     - debug:
         var: npm.stdout_lines
